'use client';
import {usePathname} from 'next/navigation';
import {useEffect} from 'react';
import {animate,stagger} from 'animejs';

export default function PageMotion(){
 const pathname=usePathname();
 useEffect(()=>{
  if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;
  const cleanups=[];const running=[];const canHover=window.matchMedia('(hover: hover) and (pointer: fine)').matches;
  const run=(target,params)=>{const resolved=typeof target==='string'?document.querySelectorAll(target):target;if(!resolved||(typeof resolved.length==='number'&&resolved.length===0))return null;const animation=animate(resolved,params);running.push(animation);return animation};
  const listen=(element,event,handler)=>{if(!canHover&&(event.startsWith('mouse')||event.startsWith('pointer')))return;element.addEventListener(event,handler);cleanups.push(()=>element.removeEventListener(event,handler))};
  const reveals=[...document.querySelectorAll('.reveal')];
  const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(!entry.isIntersecting)return;const delay=Number(entry.target.dataset.delay||0);run(entry.target,{opacity:[0,1],y:[32,0],duration:760,delay,ease:'outExpo'});observer.unobserve(entry.target)})},{threshold:.12});
  reveals.forEach(element=>{element.style.opacity='0';observer.observe(element)});cleanups.push(()=>observer.disconnect());
  run('.site-header',{opacity:[0,1],y:[-18,0],duration:600,ease:'outExpo'});
  run('.brand-mark',{scale:[.78,1],rotate:[-8,0],duration:780,ease:'outBack'});
  run('.p-node',{opacity:[.78,1],scale:[.94,1.05],delay:stagger(110),duration:1050,alternate:true,loop:true,ease:'inOutSine'});
  run('.p-link',{opacity:[0,1],delay:stagger(90),duration:620,ease:'outExpo'});
  run('.p-light-vertical',{y:[0,21],opacity:[0,1,1,0],duration:1500,loop:true,ease:'inOutSine'});
  run('.p-light-curve',{x:[0,12,17,12],y:[0,0,5,10],opacity:[0,1,1,0],delay:420,duration:1800,loop:true,ease:'inOutSine'});
  const stats=[...document.querySelectorAll('.home-stat')];
  if(stats.length){
   const statsObserver=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(!entry.isIntersecting)return;run(stats,{opacity:[0,1],y:[22,0],scale:[.96,1],delay:stagger(115),duration:720,ease:'outExpo'});stats.forEach((card,index)=>{const value=card.querySelector('.stat-number');if(!value)return;const target=Number(value.dataset.statTarget||0);const suffix=value.dataset.statSuffix||'';const counter={value:0};run(counter,{value:target,duration:1250,delay:160+index*120,ease:'outExpo',onUpdate:()=>{value.textContent=`${Math.round(counter.value)}${suffix}`},onComplete:()=>{value.textContent=`${target}${suffix}`}})});statsObserver.unobserve(entry.target)})},{threshold:.25});statsObserver.observe(document.querySelector('.number-band'));cleanups.push(()=>statsObserver.disconnect());stats.forEach(card=>{listen(card,'mouseenter',()=>{run(card,{y:-7,scale:1.025,duration:300,ease:'outBack'});run(card.querySelector('.stat-number'),{scale:[1,1.08,1.035],duration:430,ease:'outBack'})});listen(card,'mouseleave',()=>run(card,{y:0,scale:1,duration:440,ease:'outExpo'}))})}
  run('.page-hero-glow',{opacity:[.35,.8],scale:[.92,1.08],duration:4200,alternate:true,loop:true,ease:'inOutSine'});
  run('.scene-stack > div',{opacity:[0,1],x:[55,0],delay:stagger(95),duration:720,ease:'outExpo'});
  run('.result-bars i,.chart-bars i,.case-chart i',{scaleY:[0,1],transformOrigin:'bottom',delay:stagger(65),duration:850,ease:'outExpo'});
  const quoteRoute=document.querySelector('.quote-route');
  if(quoteRoute){const steps=[...quoteRoute.querySelectorAll('.route-step')];const lines=[...quoteRoute.querySelectorAll('.route-line')];const scheduled=new Set();const later=(fn,delay)=>{const id=window.setTimeout(()=>{scheduled.delete(id);fn()},delay);scheduled.add(id)};const activate=index=>{steps[index]?.classList.add('is-active');if(steps[index])run(steps[index],{scale:[.82,1.08,1],duration:520,ease:'outBack'})};const travel=index=>{const line=lines[index];if(!line)return;const progress=line.querySelector('.route-progress');const spark=line.querySelector('.route-spark');if(progress)run(progress,{scaleX:[0,1],duration:760,ease:'inOutQuad'});if(spark)run(spark,{x:[0,Math.max(0,line.clientWidth-10)],opacity:[0,1,1,0],duration:780,ease:'inOutSine'})};const cycle=()=>{steps.forEach(step=>step.classList.remove('is-active'));lines.forEach(line=>{const progress=line.querySelector('.route-progress');const spark=line.querySelector('.route-spark');if(progress)run(progress,{scaleX:0,duration:1});if(spark)run(spark,{x:0,opacity:0,duration:1})});later(()=>activate(0),120);later(()=>travel(0),650);later(()=>activate(1),1430);later(()=>travel(1),1980);later(()=>activate(2),2760);later(()=>run('.quote-reviewer',{opacity:[.55,1],scale:[.82,1.1,1],rotate:[-5,3,0],duration:720,ease:'outBack'}),3070)};cycle();const cycleId=window.setInterval(cycle,4800);cleanups.push(()=>{window.clearInterval(cycleId);scheduled.forEach(id=>window.clearTimeout(id))});run('.quote-reviewer span',{scale:[.86,1.12],opacity:[.72,1],duration:1300,alternate:true,loop:true,ease:'inOutSine'})}
  run('.float-a',{y:[-7,8],duration:2700,alternate:true,loop:true,ease:'inOutSine'});
  run('.float-b',{y:[8,-6],duration:3200,alternate:true,loop:true,ease:'inOutSine'});
  run('.result-chip,.quote-card',{y:[-4,6],delay:stagger(180),duration:2900,alternate:true,loop:true,ease:'inOutSine'});
  run('.orbit i',{scale:[.75,1.35],opacity:[.55,1],delay:stagger(220),duration:1500,alternate:true,loop:true,ease:'inOutSine'});
  document.querySelectorAll('.about-scene .scene-label').forEach(label=>{const icon=label.querySelector('svg');listen(label,'mouseenter',()=>{label.classList.add('is-active');run(label,{scale:1.12,y:-5,duration:300,ease:'outBack'});if(icon)run(icon,{rotate:[0,-10,8,0],scale:1.16,duration:480,ease:'outBack'})});listen(label,'mouseleave',()=>{label.classList.remove('is-active');run(label,{scale:1,y:0,duration:420,ease:'outExpo'});if(icon)run(icon,{rotate:0,scale:1,duration:380,ease:'outExpo'})});listen(label,'click',()=>{label.classList.add('is-active');run(label,{scale:[1,1.18,1.06],y:[0,-7,-3],duration:560,ease:'outBack'});if(icon)run(icon,{rotate:[0,-14,12,0],scale:[1,1.22,1.08],duration:560,ease:'outBack'});const id=window.setTimeout(()=>label.classList.remove('is-active'),900);cleanups.push(()=>window.clearTimeout(id))})});
  const principleCards=[...document.querySelectorAll('.principle-card')];
  if(principleCards.length){let principleIndex=0;const activatePrinciple=index=>{principleCards.forEach((card,cardIndex)=>{const active=cardIndex===index;card.classList.toggle('is-sequence-active',active);run(card,{scale:active?1.045:1,y:active?-8:0,duration:active?430:520,ease:active?'outBack':'outExpo'});const icon=card.querySelector('.principle-icon');if(icon)run(icon,{scale:active?1.14:1,rotate:active?[0,-7,5,0]:0,duration:500,ease:'outBack'})})};activatePrinciple(0);const principleLoop=window.setInterval(()=>{principleIndex=(principleIndex+1)%principleCards.length;activatePrinciple(principleIndex)},1550);cleanups.push(()=>window.clearInterval(principleLoop));principleCards.forEach((card,index)=>listen(card,'click',()=>{principleIndex=index;activatePrinciple(index)}))}
  const aboutProcess=document.querySelector('.about-process-layout');
  if(aboutProcess){const items=[...aboutProcess.querySelectorAll('.about-process-item')];const panels=[...aboutProcess.querySelectorAll('.about-stage-panel')];const dots=[...aboutProcess.querySelectorAll('.about-stage-dot')];const people=[...aboutProcess.querySelectorAll('.about-person')];let stageIndex=0;const activateStage=index=>{items.forEach((item,itemIndex)=>{const active=itemIndex===index;item.classList.toggle('is-active',active);run(item,{x:active?9:0,scale:active?1.018:1,duration:active?390:500,ease:active?'outBack':'outExpo'})});panels.forEach((panel,panelIndex)=>{const active=panelIndex===index;panel.classList.toggle('is-active',active);run(panel,{opacity:active?[0,1]:0,y:active?[15,0]:-8,scale:active?[.97,1]:.98,duration:active?540:260,ease:active?'outExpo':'inQuad'});if(active){const pieces=panel.querySelectorAll('.stage-visual-piece');if(pieces.length)run(pieces,{opacity:[0,1],y:[10,0],scale:[.9,1],delay:stagger(85),duration:560,ease:'outBack'})}});dots.forEach((dot,dotIndex)=>{dot.classList.toggle('is-active',dotIndex===index);dot.classList.toggle('is-complete',dotIndex<=index)});people.forEach((person,personIndex)=>run(person,{scale:personIndex===index%people.length?[1,1.08,1.03]:1,y:personIndex===index%people.length?-3:0,duration:520,ease:'outBack'}))};activateStage(0);const stageLoop=window.setInterval(()=>{stageIndex=(stageIndex+1)%Math.max(1,items.length);activateStage(stageIndex)},3300);cleanups.push(()=>window.clearInterval(stageLoop));items.forEach((item,index)=>listen(item,'click',()=>{stageIndex=index;activateStage(index)}));run('.about-person span',{y:[-3,3],delay:stagger(260),duration:1850,alternate:true,loop:true,ease:'inOutSine'});run('.about-collaboration svg',{scale:[.94,1.08],rotate:[-3,3],duration:1450,alternate:true,loop:true,ease:'inOutSine'})}
  document.querySelectorAll('.project-case-visual').forEach((visual,visualIndex)=>{const animated=visual.querySelectorAll('.case-animate');const bars=visual.querySelectorAll('.continuity-bars i,.traffic-bars i');const paths=[...visual.querySelectorAll('.network-path')];const metric=visual.parentElement?.querySelector('.case-metric-badge');const cycleItems=[...visual.querySelectorAll('.case-cycle-item')];if(animated.length)run(animated,{opacity:[0,1],y:[14,0],delay:stagger(90),duration:680,ease:'outExpo'});if(bars.length)run(bars,{scaleY:[0,1],transformOrigin:'bottom',delay:stagger(65),duration:820,ease:'outExpo'});if(paths.length){run(paths,{opacity:[0,1],delay:stagger(100),duration:760,ease:'outQuad'});paths.forEach((path,index)=>{const packet=path.querySelector('b');if(packet)run(packet,{x:[0,Math.max(18,path.clientWidth-8)],opacity:[0,1,1,0],delay:index*240,duration:1550+index*90,loop:true,ease:'inOutSine'})})}if(metric)run(metric,{y:[-4,5],delay:visualIndex*180,duration:2400+visualIndex*240,alternate:true,loop:true,ease:'inOutSine'});const signal=visual.querySelector('.network-signal');if(signal)run(signal,{scale:[.6,2.5],opacity:[.75,0],duration:1550,loop:true,ease:'outExpo'});if(cycleItems.length){let activeIndex=0;const activate=()=>{cycleItems.forEach((item,index)=>item.classList.toggle('is-live',index===activeIndex));const activeItem=cycleItems[activeIndex];const pulseTarget=activeItem.matches('.network-node')?activeItem.querySelector('svg'):activeItem;run(pulseTarget,{scale:[1,1.12,1],duration:520,ease:'outBack'});activeIndex=(activeIndex+1)%cycleItems.length};activate();const cycleLoop=window.setInterval(activate,1650+visualIndex*180);cleanups.push(()=>window.clearInterval(cycleLoop))}});
  document.querySelectorAll('.home-project-showcase').forEach((showcase,showcaseIndex)=>{const scenes=[...showcase.querySelectorAll('[data-home-scene]')];const dots=[...showcase.querySelectorAll('.home-showcase-dots i')];const metric=showcase.querySelector('.home-project-metric');let sceneIndex=0;const activateScene=index=>{scenes.forEach((scene,itemIndex)=>{const active=itemIndex===index;scene.classList.toggle('is-active',active);if(active){run(scene,{opacity:[0,1],x:[18,0],scale:[.975,1],duration:720,ease:'outExpo'});const pieces=scene.querySelectorAll('.home-ui-piece');if(pieces.length)run(pieces,{opacity:[0,1],y:[10,0],delay:stagger(90),duration:620,ease:'outBack'});const backupLines=scene.querySelectorAll('.home-backup-flow>i b');if(backupLines.length)run(backupLines,{scaleX:[0,1],transformOrigin:'left',delay:stagger(100),duration:760,ease:'inOutQuad'});const networkLines=scene.querySelectorAll('.net-line,.mesh-line');if(networkLines.length)run(networkLines,{opacity:[0,1],delay:stagger(75),duration:680,ease:'outQuad'});const nodes=scene.querySelectorAll('.home-net-node,.mesh-node');if(nodes.length)run(nodes,{opacity:[0,1],delay:stagger(100),duration:580,ease:'outQuad'});const chartBars=scene.querySelectorAll('.home-chart-column,.home-chart-path i');if(chartBars.length)run(chartBars,{scaleY:[0,1],transformOrigin:'bottom',delay:stagger(75),duration:720,ease:'outExpo'});const movingTask=scene.querySelector('.home-moving-task');if(movingTask)run(movingTask,{y:[0,-4,0],boxShadow:['0 10px 24px rgba(69,101,201,.12)','0 16px 34px rgba(69,101,201,.22)'],duration:1500,alternate:true,loop:true,ease:'inOutSine'})}else run(scene,{opacity:0,x:-10,scale:.985,duration:300,ease:'inQuad'})});dots.forEach((dot,dotIndex)=>dot.classList.toggle('is-active',dotIndex===index))};activateScene(0);const sceneLoop=window.setInterval(()=>{sceneIndex=(sceneIndex+1)%scenes.length;activateScene(sceneIndex)},4300+showcaseIndex*300);cleanups.push(()=>window.clearInterval(sceneLoop));if(metric)run(metric,{y:[-3,5],delay:showcaseIndex*160,duration:2500+showcaseIndex*180,alternate:true,loop:true,ease:'inOutSine'});const liveBars=showcase.querySelectorAll('.home-live-bar');if(liveBars.length)run(liveBars,{scaleX:[.08,1],transformOrigin:'left',duration:2400,alternate:true,loop:true,ease:'inOutSine'});const tokens=showcase.querySelectorAll('.home-flow-token');if(tokens.length)run(tokens,{x:[0,27],opacity:[0,1,1,0],delay:stagger(380),duration:1450,loop:true,ease:'inOutQuad'});showcase.querySelectorAll('.home-network-packet').forEach((packet,index)=>{const surface=packet.parentElement;const width=surface?.clientWidth||showcase.clientWidth;const height=surface?.clientHeight||showcase.clientHeight;const x=width*Number(packet.dataset.packetX||0);const y=height*Number(packet.dataset.packetY||0);run(packet,{x:[0,x],y:[0,y],opacity:[0,1,1,0],delay:index*420,duration:1800+index*180,loop:true,ease:'inOutSine'})})});
  document.querySelectorAll('.result-bars,.chart-bars,.case-chart').forEach(group=>{const bars=[...group.querySelectorAll('i')];bars.forEach(bar=>{listen(bar,'mouseenter',()=>{bars.filter(other=>other!==bar).forEach(other=>{other.classList.remove('bar-active');run(other,{scaleY:.76,y:4,opacity:.42,duration:280,ease:'outQuad'})});bar.classList.add('bar-active');run(bar,{scaleY:1.22,y:-8,opacity:1,duration:340,ease:'outBack'})});listen(bar,'mouseleave',()=>{bar.classList.remove('bar-active');bars.forEach(other=>run(other,{scaleY:1,y:0,opacity:1,duration:420,ease:'outExpo'}))})})});
  document.querySelectorAll('.scene-stack > div').forEach(card=>{const icon=card.querySelector('.service-icon');const copy=card.querySelector('b');listen(card,'mouseenter',()=>{card.classList.add('is-hovered');run(card,{y:-7,scale:1.075,duration:320,ease:'outBack'});if(icon)run(icon,{rotate:-7,scale:1.14,duration:360,ease:'outBack'});if(copy)run(copy,{x:7,duration:320,ease:'outQuad'})});listen(card,'mouseleave',()=>{card.classList.remove('is-hovered');run(card,{y:0,scale:1,duration:460,ease:'outExpo'});if(icon)run(icon,{rotate:0,scale:1,duration:420,ease:'outExpo'});if(copy)run(copy,{x:0,duration:420,ease:'outExpo'})})});
  document.querySelectorAll('.service-card,.service-detail,.price-card,.principle-grid > div,.process-item,.contact-method,.case-visual,.form-panel').forEach(card=>{listen(card,'mouseenter',()=>run(card,{y:-7,scale:1.035,duration:300,ease:'outBack'}));listen(card,'mouseleave',()=>run(card,{y:0,scale:1,duration:440,ease:'outExpo'}))});
  const projectStory=document.querySelector('.project-story');
  if(projectStory){const discovery=projectStory.querySelector('.discovery-board');const system=projectStory.querySelector('.solution-system');const people=projectStory.querySelectorAll('.project-person');const paths=projectStory.querySelectorAll('.discussion-path');const insight=projectStory.querySelector('.insight-chip');const systemParts=projectStory.querySelectorAll('.system-metrics>div,.workflow-row');const projectTimers=new Set();const later=(fn,delay)=>{const id=window.setTimeout(()=>{projectTimers.delete(id);fn()},delay);projectTimers.add(id)};const cycle=()=>{run(system,{opacity:0,y:24,scale:.94,duration:1});run(discovery,{opacity:[0,1],scale:[.96,1],duration:650,ease:'outExpo'});run(people,{opacity:[0,1],y:[15,0],delay:stagger(180),duration:760,ease:'outBack'});run(paths,{scaleX:[0,1],transformOrigin:'center',delay:720,duration:900,ease:'inOutQuad'});run(insight,{opacity:[0,1],y:[8,0],delay:1750,duration:650,ease:'outBack'});later(()=>{run(discovery,{opacity:.32,scale:.965,duration:720,ease:'outQuad'});run(system,{opacity:[0,1],y:[25,0],scale:[.94,1],duration:760,ease:'outExpo'});run(systemParts,{opacity:[0,1],x:[18,0],delay:stagger(75),duration:600,ease:'outExpo'})},4050);later(()=>{run(system,{opacity:[1,0],y:[0,-12],scale:[1,.975],duration:520,ease:'inOutQuad'});run(discovery,{opacity:[.32,1],scale:[.965,1],duration:520,ease:'outQuad'})},8600)};cycle();const projectLoop=window.setInterval(cycle,9400);cleanups.push(()=>{window.clearInterval(projectLoop);projectTimers.forEach(id=>window.clearTimeout(id))});run('.project-person .avatar',{y:[-3,3],delay:stagger(240),duration:1900,alternate:true,loop:true,ease:'inOutSine'})}
  const projectCta=document.querySelector('.project-cta');
  if(projectCta){const glow=projectCta.querySelector('.project-cta-glow');if(glow)run(glow,{x:[0,projectCta.clientWidth+260],opacity:[0,.65,0],duration:3800,loop:true,ease:'inOutSine'});listen(projectCta,'mouseenter',()=>run(projectCta,{y:-4,scale:1.012,duration:300,ease:'outQuad'}));listen(projectCta,'mouseleave',()=>run(projectCta,{y:0,scale:1,duration:420,ease:'outExpo'}))}
  const contactChat=document.querySelector('.contact-scene');
  if(contactChat){const messages=[...contactChat.querySelectorAll('.chat-message')];const available=contactChat.querySelector('.availability');const chatTimers=new Set();const later=(fn,delay)=>{const id=window.setTimeout(()=>{chatTimers.delete(id);fn()},delay);chatTimers.add(id)};const chatCycle=()=>{messages.forEach(message=>run(message,{opacity:0,y:10,scale:.96,duration:1}));if(available)run(available,{opacity:0,y:7,duration:1});messages.forEach((message,index)=>later(()=>run(message,{opacity:[0,1],y:[10,0],scale:[.96,1],duration:520,ease:'outBack'}),220+index*760));if(available)later(()=>run(available,{opacity:[0,1],y:[7,0],duration:480,ease:'outExpo'}),4200);later(()=>{run(messages,{opacity:0,y:-5,duration:420,ease:'inQuad'});if(available)run(available,{opacity:0,duration:320,ease:'inQuad'})},6600)};chatCycle();const chatLoop=window.setInterval(chatCycle,7300);cleanups.push(()=>{window.clearInterval(chatLoop);chatTimers.forEach(id=>window.clearTimeout(id))})}
  const schedule=document.querySelector('.schedule');
  if(schedule){const clock=schedule.querySelector('svg');run(schedule,{borderColor:['#d9e5f3','#9fdec9'],boxShadow:['0 12px 28px rgba(33,66,108,.07)','0 16px 34px rgba(30,164,121,.14)'],duration:2400,alternate:true,loop:true,ease:'inOutSine'});if(clock)run(clock,{rotate:[-7,7],scale:[.96,1.06],duration:1150,alternate:true,loop:true,ease:'inOutSine'});listen(schedule,'mouseenter',()=>run(schedule,{scale:1.025,y:-4,duration:280,ease:'outQuad'}));listen(schedule,'mouseleave',()=>run(schedule,{scale:1,y:0,duration:400,ease:'outExpo'}))}
  const art=document.querySelector('.page-hero-art');
  if(art&&!art.closest('.page-hero-pricing')){listen(art,'pointermove',event=>{const rect=art.getBoundingClientRect();const px=(event.clientX-rect.left)/rect.width-.5;const py=(event.clientY-rect.top)/rect.height-.5;run('.page-scene',{rotateY:px*3.2,rotateX:-py*2.6,x:px*7,y:py*5,duration:480,ease:'outQuad'})});listen(art,'pointerleave',()=>run('.page-scene',{rotateY:0,rotateX:0,x:0,y:0,duration:700,ease:'outExpo'}))}
  const proposalSheet=document.querySelector('.proposal-sheet');
  if(proposalSheet){listen(proposalSheet,'mouseenter',()=>run(proposalSheet,{scale:1.04,y:-5,rotate:3,duration:280,ease:'outQuad'}));listen(proposalSheet,'mouseleave',()=>run(proposalSheet,{scale:1,y:0,rotate:3,duration:380,ease:'outExpo'}))}
  const priceSeal=document.querySelector('.price-seal');
  if(priceSeal){const ring=priceSeal.querySelector('.seal-ring');const stamp=()=>{run(priceSeal,{opacity:[0,1],y:[-62,5,-3,0],scale:[1.42,.9,1.07,1],rotate:[-24,-8],duration:920,ease:'outBack'});if(ring)run(ring,{opacity:[.72,0],scale:[.55,1.65],duration:820,ease:'outExpo'})};const firstStamp=window.setTimeout(stamp,520);const stampLoop=window.setInterval(stamp,4300);cleanups.push(()=>{window.clearTimeout(firstStamp);window.clearInterval(stampLoop)})}
  document.querySelectorAll('.hero,.page-hero').forEach(hero=>{listen(hero,'pointermove',event=>{const rect=hero.getBoundingClientRect();const px=Math.max(0,Math.min(1,(event.clientX-rect.left)/rect.width));const py=Math.max(0,Math.min(1,(event.clientY-rect.top)/rect.height));hero.style.setProperty('--grid-x',`${px*100}%`);hero.style.setProperty('--grid-y',`${py*100}%`);hero.style.setProperty('--grid-ry',`${(px-.5)*2.4}deg`);hero.style.setProperty('--grid-rx',`${(.5-py)*2}deg`)});listen(hero,'pointerleave',()=>{hero.style.setProperty('--grid-x','50%');hero.style.setProperty('--grid-y','45%');hero.style.setProperty('--grid-ry','0deg');hero.style.setProperty('--grid-rx','0deg')})});
  document.querySelectorAll('.button,.nav-wrap nav > a').forEach(button=>{listen(button,'mouseenter',()=>run(button,{scale:1.035,duration:220,ease:'outQuad'}));listen(button,'mouseleave',()=>run(button,{scale:1,duration:300,ease:'outQuad'}))});
  return()=>{cleanups.forEach(fn=>fn());running.forEach(animation=>animation.cancel?.())};
 },[pathname]);
 return null;
}
